
## using panda for data analaysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
# read cv file
df = pd.read_csv('./vgsales.csv')

In [3]:
pd

In [4]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

## q1 Which company is the most common video game publisher?

In [5]:
most_common=df[["Publisher"]].mode()
most_common

         Publisher
0  Electronic Arts

## q2 Whatâ€™s the most common platform?

In [6]:
most_common_2=df[["Platform"]].mode()
most_common_2

  Platform
0       DS

## q3 What about the most common genre?

In [7]:
most_common_3=df[['Genre']].mode()
most_common_3

    Genre
0  Action

## q4 What are the top 20 highest grossing games?

In [8]:
data_by_nameandglobalsale=df.groupby(['Name','Global_Sales'])
data_by_nameandglobalsale.describe()

                                                      Rank               \
                                                     count     mean std
Name                                    Global_Sales
'98 Koshien                             0.41           1.0   4756.0 NaN
.hack//G.U. Vol.1//Rebirth              0.17           1.0   8359.0 NaN
.hack//G.U. Vol.2//Reminisce            0.23           1.0   7109.0 NaN
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16           1.0   8604.0 NaN
.hack//G.U. Vol.3//Redemption           0.17           1.0   8306.0 NaN
...                                                    ...      ...  ..
uDraw Studio                            2.46           1.0    628.0 NaN
uDraw Studio: Instant Artist            0.02           1.0  15526.0 NaN
                                        0.19           1.0   7837.0 NaN
wwe Smackdown vs. Raw 2006              3.00           1.0    471.0 NaN
Â¡Shin Chan Flipa en colores!            0.14           1.0   9137.0 NaN

                                                                        \
                                                          min      25%
Name                                    Global_Sales
'98 Koshien                             0.41           4756.0   4756.0
.hack//G.U. Vol.1//Rebirth              0.17           8359.0   8359.0
.hack//G.U. Vol.2//Reminisce            0.23           7109.0   7109.0
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16           8604.0   8604.0
.hack//G.U. Vol.3//Redemption           0.17           8306.0   8306.0
...                                                       ...      ...
uDraw Studio                            2.46            628.0    628.0
uDraw Studio: Instant Artist            0.02          15526.0  15526.0
                                        0.19           7837.0   7837.0
wwe Smackdown vs. Raw 2006              3.00            471.0    471.0
Â¡Shin Chan Flipa en colores!            0.14           9137.0   9137.0

                                                                        \
                                                          50%      75%
Name                                    Global_Sales
'98 Koshien                             0.41           4756.0   4756.0
.hack//G.U. Vol.1//Rebirth              0.17           8359.0   8359.0
.hack//G.U. Vol.2//Reminisce            0.23           7109.0   7109.0
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16           8604.0   8604.0
.hack//G.U. Vol.3//Redemption           0.17           8306.0   8306.0
...                                                       ...      ...
uDraw Studio                            2.46            628.0    628.0
uDraw Studio: Instant Artist            0.02          15526.0  15526.0
                                        0.19           7837.0   7837.0
wwe Smackdown vs. Raw 2006              3.00            471.0    471.0
Â¡Shin Chan Flipa en colores!            0.14           9137.0   9137.0

                                                               Year          \
                                                          max count    mean
Name                                    Global_Sales
'98 Koshien                             0.41           4756.0   1.0  1998.0
.hack//G.U. Vol.1//Rebirth              0.17           8359.0   1.0  2006.0
.hack//G.U. Vol.2//Reminisce            0.23           7109.0   1.0  2006.0
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16           8604.0   1.0  2006.0
.hack//G.U. Vol.3//Redemption           0.17           8306.0   1.0  2007.0
...                                                       ...   ...     ...
uDraw Studio                            2.46            628.0   1.0  2010.0
uDraw Studio: Instant Artist            0.02          15526.0   1.0  2011.0
                                        0.19           7837.0   1.0  2011.0
wwe Smackdown vs. Raw 2006              3.00            471.0   0.0     NaN
Â¡Shin Chan Flipa en colores!            0.14           9137.0   1.0  2007.0

                                                      ... JP_Sales        \
                                                      ...      75%   max
Name                                    Global_Sales  ...
'98 Koshien                             0.41          ...     0.12  0.12
.hack//G.U. Vol.1//Rebirth              0.17          ...     0.17  0.17
.hack//G.U. Vol.2//Reminisce            0.23          ...     0.00  0.00
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16          ...     0.16  0.16
.hack//G.U. Vol.3//Redemption           0.17          ...     0.17  0.17
...                                                   ...      ...   ...
uDraw Studio                            2.46          ...     0.00  0.00
uDraw Studio: Instant Artist            0.02          ...     0.00  0.00
                                        0.19          ...     0.00  0.00
wwe Smackdown vs. Raw 2006              3.00          ...     0.00  0.00
Â¡Shin Chan Flipa en colores!            0.14          ...     0.14  0.14

                                                     Other_Sales            \
                                                           count  mean std
Name                                    Global_Sales
'98 Koshien                             0.41                 1.0  0.03 NaN
.hack//G.U. Vol.1//Rebirth              0.17                 1.0  0.00 NaN
.hack//G.U. Vol.2//Reminisce            0.23                 1.0  0.03 NaN
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16                 1.0  0.00 NaN
.hack//G.U. Vol.3//Redemption           0.17                 1.0  0.00 NaN
...                                                          ...   ...  ..
uDraw Studio                            2.46                 1.0  0.20 NaN
uDraw Studio: Instant Artist            0.02                 1.0  0.00 NaN
                                        0.19                 1.0  0.02 NaN
wwe Smackdown vs. Raw 2006              3.00                 1.0  0.41 NaN
Â¡Shin Chan Flipa en colores!            0.14                 1.0  0.00 NaN

                                                                              \
                                                       min   25%   50%   75%
Name                                    Global_Sales
'98 Koshien                             0.41          0.03  0.03  0.03  0.03
.hack//G.U. Vol.1//Rebirth              0.17          0.00  0.00  0.00  0.00
.hack//G.U. Vol.2//Reminisce            0.23          0.03  0.03  0.03  0.03
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16          0.00  0.00  0.00  0.00
.hack//G.U. Vol.3//Redemption           0.17          0.00  0.00  0.00  0.00
...                                                    ...   ...   ...   ...
uDraw Studio                            2.46          0.20  0.20  0.20  0.20
uDraw Studio: Instant Artist            0.02          0.00  0.00  0.00  0.00
                                        0.19          0.02  0.02  0.02  0.02
wwe Smackdown vs. Raw 2006              3.00          0.41  0.41  0.41  0.41
Â¡Shin Chan Flipa en colores!            0.14          0.00  0.00  0.00  0.00


                                                       max
Name                                    Global_Sales
'98 Koshien                             0.41          0.03
.hack//G.U. Vol.1//Rebirth              0.17          0.00
.hack//G.U. Vol.2//Reminisce            0.23          0.03
.hack//G.U. Vol.2//Reminisce (jp sales) 0.16          0.00
.hack//G.U. Vol.3//Redemption           0.17          0.00
...                                                    ...
uDraw Studio                            2.46          0.20
uDraw Studio: Instant Artist            0.02          0.00
                                        0.19          0.02
wwe Smackdown vs. Raw 2006              3.00          0.41
Â¡Shin Chan Flipa en colores!            0.14          0.00

[16379 rows x 48 columns]

In [10]:
data_by_nameandglobalsale.head(20)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [43]:

top_20=data_by_nameandglobalsale.head(20).sort_values('Global_Sales', ascending=False).head(20)
top_20
####the final answer for q4 here####

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
10,11,Nintendogs,DS,2005.0,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76
11,12,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
12,13,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10
13,14,Wii Fit,Wii,2007.0,Sports,Nintendo,8.94,8.03,3.60,2.15,22.72
14,15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
15,16,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
18,19,Super Mario World,SNES,1990.0,Platform,Nintendo,12.78,3.75,3.54,0.55,20.61
19,20,Brain Age: Train Your Brain in Minutes a Day,DS,2005.0,Misc,Nintendo,4.75,9.26,4.16,2.05,20.22

## q5 For North American video game sales, whatâ€™s the median?

In [71]:
the_median = df[['NA_Sales']].median()[0]

print(f'the median is => {the_median}')
# Provide a secondary output showing ten games surrounding the median sales output
median_ten_game = df[df["NA_Sales"] == the_median][["Name"]].head(10)
print(median_ten_game)
# assume that games with same median value are sorted in descending order

the median is => 0.08
                                                   Name
446                                   Dragon Warrior IV
497         World Soccer Winning Eleven 7 International
1617                             Farming Simulator 2015
1926                          Pro Evolution Soccer 2008
2067  Winning Eleven: Pro Evolution Soccer 2007 (All...
2373                           Phantasy Star Portable 2
2579                               The Sims 2: Castaway
3186                                     SingStar Queen
3503                                         Top Spin 3
3703               Sonic & All-Stars Racing Transformed

## q6 For the top-selling game of all time, how many standard deviations above/below the mean are its sales for North America?

In [42]:
standard_deviations=df['NA_Sales'].std()
# print(standard_deviations)
the_mean=df['NA_Sales'].mean()
top_seling=df["NA_Sales"].iloc[0]
the_result=(-the_mean+top_seling)/standard_deviations
print(the_result)

50.47898767479108

## q7 The Nintendo Wii seems to have outdone itself with games. How does its average number of sales compare with all of the other platforms?

In [46]:
The_Nintendo_Wii=df[df['Platform']=="Wii"].mean()
print(The_Nintendo_Wii.Global_Sales.mean())

0.6994037735849057

## q8 Come up with 3 more questions that can be answered with this data set.

In [47]:
#q1 the What about the most common NAME?
most_common_4=df[['Name']].mode()
most_common_4

                          Name
0  Need for Speed: Most Wanted

In [48]:
#q2  What is standard devision for jp sales ?

standard_deviation = df[['JP_Sales']].std()[0]
standard_deviation

0.30929064808220297

In [50]:
#q3 give us the data for  fifa 14 game?
fifa_data = df[ df['Name']=='FIFA 14' ]
fifa_data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
112,113,FIFA 14,PS3,2013.0,Sports,Electronic Arts,0.78,4.32,0.07,1.73,6.90
256,257,FIFA 14,X360,2013.0,Sports,Electronic Arts,0.92,2.93,0.01,0.46,4.31
493,494,FIFA 14,PS4,2013.0,Sports,Electronic Arts,0.61,1.85,0.11,0.33,2.90
1698,1700,FIFA 14,XOne,2013.0,Sports,Electronic Arts,0.41,0.66,0.00,0.12,1.19
3988,3990,FIFA 14,PSV,2013.0,Sports,Electronic Arts,0.11,0.25,0.01,0.13,0.50
4503,4505,FIFA 14,PC,2013.0,Sports,Electronic Arts,0.01,0.36,0.00,0.06,0.43
4538,4540,FIFA 14,Wii,2013.0,Sports,Electronic Arts,0.00,0.38,0.00,0.05,0.43
6661,6663,FIFA 14,3DS,2013.0,Sports,Electronic Arts,0.00,0.23,0.00,0.03,0.25
7034,7036,FIFA 14,PSP,2013.0,Sports,Electronic Arts,0.00,0.16,0.00,0.07,0.23

In [1]:
def test():

    def assert_equal(actual,expected):
        
        assert actual == expected, f"Expected {expected} but got {actual}"
        
        assert_equal(most_common_platform, "DS")
        assert_equal(most_common_publisher, "Electronic Arts")
        assert_equal(most_common_genre, "Action")
        
        assert_equal(top_20.iloc[1].Name, 'Super Mario Bros')
            
        assert_equal(top_20.iloc[19].Name, 'Brain Age: Train Your Brain in Minutes a Day')
    
        assert_equal(the_median, 0.08)
        
        assert_equal(fifa_data.iloc[0].Platform, 'PS3')
        assert_equal(median_ten_game.iloc[0].Name, 'Dragon Warrior IV')
        

    print("Success!!!")

test()

Success!!!